version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform 1.5.x"
      - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - echo "Initializing Terraform"
      - terraform init -input=false
      - echo "Applying Terraform"
      - terraform destroy -auto-approve -input=false

